### ISSUE TITLE
[BUG] APM making my app unavailable

### ISSUE THREAD

**Issue by se** [elastic/apm-agent-dotnet#1483]
### APM Agent version
The version `1.10.0` of the `Elastic.Apm.NetCoreAll` nuget package used

### Environment

**Operating system and version:**
`Ubuntu Server 19.04`

**.NET Framework/Core name and version**
```
SDK 3.1.412
ASP.NET Core Runtime 3.1.18
```

**Application Target Framework(s)**
`netcoreapp3.1`

**Additional Information**
- My apm behind a CloudFlare Web Proxy

**Elastic Search versions**
#### Images
```
docker.elastic.co/kibana/kibana:7.14.1
docker.elastic.co/apm/apm-server:7.14.1
docker.elastic.co/elasticsearch/elasticsearch:7.14.1
```
#### Config
docker-compose.yml
```yml
version: '2.2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=true
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elk:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - elk
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      SERVERNAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: MY-KIBANA-SYSTEM-PASSWORD
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elk
  apm-server:
    image: docker.elastic.co/apm/apm-server:7.14.1
    container_name: apm-server
    ports:
      - 8200:8200
    environment:
      SERVERNAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: apm_system
      ELASTICSEARCH_PASSWORD: MY-APM-SYSTEM-PASSWORD
    volumes:
      - ./apm-server.yml:/usr/share/apm-server/apm-server.yml:ro
    networks:
      - elk
volumes:
  elk:
    driver: local

networks:
  elk:
    driver: bridge
```

elasticsearch.yml
```yml
cluster.name: "my-cluster-name"
network.host: 0.0.0.0
xpack.license.self_generated.type: basic
xpack.security.enabled: true
xpack.security.authc.api_key.enabled: true
discovery.type: single-node
```

kibana.yml
```yml
server.host: 0.0.0.0
server.publicBaseUrl: https://apm
```

apm-server.yml
```yml
apm-server:
  host: 0.0.0.0
apm-server.auth.secret_token: "[HIDDEN]"
apm-server.kibana:
  username: "kibana_system"
  password: "[HIDDEN]"
  enabled: true
  host: "http://kibana:5601"
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "[HIDDEN]"
  enabled: true
apm-server.ilm.setup.enabled: true
```

### Describe the bug
My application is getting down in random times. Sometimes it is working fine for 4 hours, sometime 2 hours, sometimes 1 hour and down. When I check latest logs I'm seeing 2 different logs but mostly this;

```
app-1.o0nqjhec17xm@do-docker-node01    | fail: Elastic.Apm[0]
app-1.o0nqjhec17xm@do-docker-node01    |       {CentralConfigFetcher} Exception was thrown while fetching configuration from APM Server and parsing it. ETag: `<null>'. URL: `https://apm/config/v1/agents?service.name=APP&service.environment=Demo'. Apm Server base URL: `https://apm/'. WaitInterval: 5m. dbgIterationsCount: 164.
app-1.o0nqjhec17xm@do-docker-node01    |       +-> Request:
app-1.o0nqjhec17xm@do-docker-node01    |           Method: GET, RequestUri: 'https://apm/config/v1/agents?service.name=APP&service.environment=Demo', Version: 1.1, Content: <null>, Headers:
app-1.o0nqjhec17xm@do-docker-node01    |           {
app-1.o0nqjhec17xm@do-docker-node01    |             User-Agent: elasticapm-dotnet/1.10.0+ecfe0d02ee33d22706236b4cb31126d15a02507f
app-1.o0nqjhec17xm@do-docker-node01    |             User-Agent: System.Net.Http/4.700.21.36305
app-1.o0nqjhec17xm@do-docker-node01    |             User-Agent: .NET_Core/3.1.18
app-1.o0nqjhec17xm@do-docker-node01    |             Authorization: Bearer [HIDDEN]
app-1.o0nqjhec17xm@do-docker-node01    |             Request-Id: |298b5f2c-44a72cfcb13178db.
app-1.o0nqjhec17xm@do-docker-node01    |           }
app-1.o0nqjhec17xm@do-docker-node01    |       +-> Response:
app-1.o0nqjhec17xm@do-docker-node01    |           StatusCode: 503, ReasonPhrase: 'Service Unavailable', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
app-1.o0nqjhec17xm@do-docker-node01    |           {
app-1.o0nqjhec17xm@do-docker-node01    |             Date: Tue, 07 Sep 2021 03:46:51 GMT
app-1.o0nqjhec17xm@do-docker-node01    |             Connection: keep-alive
app-1.o0nqjhec17xm@do-docker-node01    |             Cache-Control: must-revalidate, max-age=300
app-1.o0nqjhec17xm@do-docker-node01    |             X-Content-Type-Options: nosniff
app-1.o0nqjhec17xm@do-docker-node01    |             CF-Cache-Status: DYNAMIC
app-1.o0nqjhec17xm@do-docker-node01    |             NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
app-1.o0nqjhec17xm@do-docker-node01    |             Server: cloudflare
app-1.o0nqjhec17xm@do-docker-node01    |             CF-RAY: 68acf3cf8df9597d-AMS
app-1.o0nqjhec17xm@do-docker-node01    |             Alt-Svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400, h3-28=":443"; ma=86400, h3-27=":443"; ma=86400
app-1.o0nqjhec17xm@do-docker-node01    |             Content-Type: text/plain; charset=utf-8
app-1.o0nqjhec17xm@do-docker-node01    |             Content-Length: 83
app-1.o0nqjhec17xm@do-docker-node01    |           }
app-1.o0nqjhec17xm@do-docker-node01    |       +-> Response body [length: 83]:
app-1.o0nqjhec17xm@do-docker-node01    |           {"error":"{\"statusCode\":403,\"error\":\"Forbidden\",\"message\":\"Forbidden\"}"}
app-1.o0nqjhec17xm@do-docker-node01    |
app-1.o0nqjhec17xm@do-docker-node01    | Elastic.Apm.BackendComm.CentralConfig.CentralConfigFetcher+FailedToFetchConfigException: HTTP status code is Service Unavailable (503) which most likely means that APM Server supports the central configuration endpoint and Kibana connection is enabled, but Kibana connection is unavailable
app-1.o0nqjhec17xm@do-docker-node01    |    at Elastic.Apm.BackendComm.CentralConfig.CentralConfigResponseParser.InterpretResponseStatusCode(HttpResponseMessage httpResponse, WaitInfoS waitInfo)
app-1.o0nqjhec17xm@do-docker-node01    |    at Elastic.Apm.BackendComm.CentralConfig.CentralConfigResponseParser.ParseHttpResponse(HttpResponseMessage httpResponse, String httpResponseBody)
app-1.o0nqjhec17xm@do-docker-node01    |    at Elastic.Apm.BackendComm.CentralConfig.CentralConfigFetcher.WorkLoopIteration()
```

And sometime this;

```
{PayloadSenderV2} Failed sending event. Events intake API absolute URL: http://localhost:8200/intake/v2/events. APM Server response: status code: ServiceUnavailable, content:
      {"accepted":0,"errors":[{"message":"queue is full"}]}
```

### To Reproduce

My config is;

#### Environment Variables
```env
ELASTIC_APM_ENVIRONMENT=Demo
ELASTIC_APM_CLOUD_PROVIDER=none
ELASTIC_APM_SECRET_TOKEN=MY-SECRET-TOKEN
ELASTIC_APM_SERVER_URLS=https://apm/
ELASTIC_APM_SERVICE_NAME=APP
```

#### Code
```csharp
app.UseElasticApm(configuration, new HttpDiagnosticsSubscriber());
```

#### Expected behavior
Should be working fine even APM server is down.

#### Actual behavior
Making application is down and unavailable. When i completely disable the APM in code, it is working fine.
