### ISSUE TITLE
Profiler: allow open upper bound version for instrumented libraries

### ISSUE THREAD

**Issue by z1c0** [elastic/apm-agent-dotnet#1979]
Currently, all instrumented libraries listed in `integrations.yml` have well-defined upper (and lower) bounds for their version.

Example:

```yml
...
  - target:
      assembly: Oracle.ManagedDataAccess
      type: Oracle.ManagedDataAccess.Client.OracleCommand
      method: ExecuteNonQueryAsync
      signature_types:
      - System.Threading.Tasks.Task`1<System.Int32>
      - System.Threading.CancellationToken
      minimum_version: 2.0.0
      maximum_version: 2.*.*
...
```

Instead of constraining `maximum_version` to a well-defined value we want an open upper bound here, so opting in to instrument newer versions of a library happens automatically.
